//creation_time - Fri Aug 02 11:51:54 UTC 2024
(function(){ 
var embed;embed=function(){var W='\n',X=0,Y=1,Z=2,$=10,_=3,ab='script',bb='$',cb='//',db='/',eb='^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$',fb='',gb='ent-id',hb='data-wfx-namespace',ib='id',jb='wfx.desktop.embed.nocache.script',kb='embed',lb='_',mb='bootstrap',nb='begin',ob='gwt.codesvr.embed=',pb='gwt.codesvr=',qb='startup',rb='DUMMY',sb='currentScript',tb='iframe',ub='position:absolute; width:0; height:0; border:none; left: -1000px;',vb=' top: -1000px;',wb='Whatfix iframe - intentionally left blank',xb='aria-hidden',yb='true',zb='BODY',Ab='FRAMESET',Bb='body',Cb='escapeRequireTrustedTypes',Db='<html><head><\/head><body><\/body><\/html>',Eb='CSS1Compat',Fb='<!doctype html>',Gb='firefox',Hb='html',Ib='head',Jb='undefined',Kb='readystatechange',Lb='data-wfx-attr',Mb='javascript',Nb='Failed to load ',Ob='https:',Pb='whatfix.com',Qb='quickolabs.com',Rb='anonymous',Sb='moduleStartup',Tb='scriptTagAdded',Ub='moduleRequested',Vb='meta',Wb='name',Xb='embed::',Yb='::',Zb='gwt:property',$b='content',_b='=',ac='gwt:onPropertyErrorFn',bc='Bad handler "',cc='" for "gwt:onPropertyErrorFn"',dc='gwt:onLoadErrorFn',ec='" for "gwt:onLoadErrorFn"',fc='#',gc='?',hc='img',ic='clear.cache.gif',jc='baseUrl',kc='embed.nocache.js',lc='/embed/',mc='base',nc='user.agent',oc='webkit',pc='safari',qc='msie',rc=11,sc='ie10',tc=9,uc='ie9',vc=8,wc='ie8',xc='gecko',yc='gecko1_8',zc=4,Ac='selectingPermutation',Bc='embed.devmode.js',Cc='355445A86D2101B03C1A1E7B87FF214B',Dc='57EFE8C0AA5820FAA1F507F771FE4E2C',Ec='6F5BB5804FF4A2BE2BFDC6ABFD037BAF',Fc='C5B9BB94695CDEAFFB8511F767BAA56B',Gc='C84DE5987EF6E62AB299501C653AB7BB',Hc=':',Ic='.cache.js',Jc='loadExternalRefs',Kc='end',Lc='http:',Mc='file:',Nc='_gwt_dummy_',Oc='__gwtDevModeHook:embed',Pc='Ignoring non-whitelisted Dev Mode URL: ',Qc=':moduleBase';var o=window;var p=document;function q(){try{throw new Error}catch(a){var b=a.stack.split(W);var c=null;for(var d=X;d<b.length;d++){var e=b[d].trim();var f=e.match(/(?:at\s+)?(?:\S+\s+)?(?:\(?.*\)?@)?(\S+):(\d+):(\d+)/);if(f){var g=f[Y];var h=parseInt(f[Z],$);var i=parseInt(f[_],$);if(g&&(h&&i)){c=b[d];break}}}if(c){var j=document.getElementsByTagName(ab);for(var d=X;d<j.length;d++){if(j[d].src&&c.indexOf(j[d].src)!==-1){return j[d]}}}return null}}
var r=document.currentScript;if(r==null){r=q()}var s=function t(a){var b,c=bb;b=a.indexOf(cb)!==-1?a.split(a.split(db)[Z]):a.split(a.split(db)[X]);var d=eb;var e=b[Y].split(db);var f=RegExp(d);for(var g=X;g<e.length;g++){if(f.exec(e[g])){return e[g].replace(/-/g,fb)}}var h;if(r){h=r.getAttribute(gb)}return h&&h!=fb?h:c};var u=s(r.src);var v=fb;if(window.frameElement&&window.frameElement.hasAttribute(hb)){v=window.frameElement.getAttribute(hb)}else if(r&&(!r.getAttribute(ib)||r.getAttribute(ib).indexOf(jb)===-1)||window.__wfx_desktop_editor&&window._wfx_desktop_app){v=kb+lb+u}if(v&&window[v]){return}if(v){window[v]={};window[v].embed=embed}else{window.embed=embed}A(mb,nb);function w(){var a=o.location.search;return a.indexOf(ob)!=-1||a.indexOf(pb)!=-1}
function A(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:kb,sessionId:o.__gwtStatsSessionId,subSystem:qb,evtGroup:a,millis:(new Date).getTime(),type:b})}}
embed.__sendStats=A;embed.__moduleName=kb;embed.__errFn=null;embed.__moduleBase=rb;embed.__softPermutationId=X;embed.__computePropValue=null;embed.__getPropMap=null;embed.__installRunAsyncCode=function(){};embed.__gwtStartLoadingFragment=function(){return null};embed.__gwt_isKnownPropertyValue=function(){return false};embed.__gwt_getMetaProperty=function(){return null};var B=null;var C=o.__gwt_activeModules=o.__gwt_activeModules||{};C[kb]={moduleName:kb};embed.__moduleStartupDone=function(e){var f=C[kb].bindings;C[kb].bindings=function(){var a=f?f():{};var b=e[embed.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};function D(){function f(){try{throw new Error}catch(a){var b=X,c=/.*at [^(]*\((.*):(.+):(.+)\)$/ig.exec(a.stack),d=c&&c[Y]||false,e=document.getElementsByTagName(ab);for(;b<e.length;b++){if(e[b].src===d){return e[b]}}return null}}
(function(){if(!(sb in document)){Object.defineProperty(document,sb,{get:f})}}())}
var F;function G(){H();return F}
function H(){if(F){return}var c=p.createElement(tb);c.id=kb;c.style.cssText=ub+vb;c.tabIndex=-1;if(c.id.indexOf(kb)>-1){c.title=wb;c.setAttribute(xb,yb)}if(p.body.tagName&&p.body.tagName.toUpperCase()===zb){p.body.appendChild(c)}else if(p.body.tagName&&p.body.tagName.toUpperCase()===Ab){p.body.parentNode.appendChild(c)}else{p.getElementsByTagName(Bb)[X].appendChild(c)}F=c.contentWindow.document;F.open();try{I(F)}catch(b){if(window.trustedTypes&&window.trustedTypes.createPolicy){var d=window.trustedTypes.createPolicy(Cb,{createHTML:function(a){return a}});var e=d.createHTML(doctype+Db);F.write(e)}}F.close()}
function I(a){var b=document.compatMode==Eb?Fb:fb;if(navigator.userAgent.toLowerCase().indexOf(Gb)>-1){a.write(b+Db);return}var c=a.documentElement;if(!c){var d=a.createElement(Hb);a.appendChild(d);c=a.documentElement}var e=c.getElementsByTagName(Ib)[X];if(!e){e=a.createElement(Ib);c.appendChild(e)}var f=c.getElementsByTagName(Bb)[X];if(!f){f=a.createElement(Bb);c.appendChild(f)}if(b&&(a.implementation&&a.implementation.createDocumentType)){var g=a.implementation.createDocumentType(Hb,fb,fb);a.insertBefore(g,a.documentElement)}}
function J(i){function j(a){function b(){if(typeof p.readyState==Jb){return typeof p.body!=Jb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(Kb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(Kb,d,false)}var e=setInterval(function(){d()},$)}
function k(a){a.setAttribute(hb,v);l(a);m(a)}
function l(a){if(r){for(var b=X;b<r.attributes.length;b++){var c=r.attributes[b];if(c.name.startsWith(Lb)){a.setAttribute(c.name,c.value)}}}}
function m(a){if(u){a.setAttribute(gb,u)}}
function n(c){var d=G();var e=d.body;var f=d.createElement(ab);f.language=Mb;try{f.src=c;k(f)}catch(b){if(window.trustedTypes&&window.trustedTypes.createPolicy){var g=window.trustedTypes.createPolicy(Cb,{createScriptURL:function(a){return a}});f.src=g.createScriptURL(c);k(f)}}if(embed.__errFn){f.onerror=function(){embed.__errFn(kb,new Error(Nb+c))}}try{if(embed&&(embed.__moduleBase&&(c&&c.startsWith(Ob)))){var h=new URL(embed.__moduleBase);if(h&&(h.hostname&&(h.hostname.indexOf(Pb)>-1||h.hostname.indexOf(Qb)>-1)))f.crossOrigin=Rb}}catch(a){}e.appendChild(f);A(Sb,Tb)}
A(Sb,Ub);j(function(){n(i)})}
embed.__startLoadingFragment=function(a){return M(a)};embed.__installRunAsyncCode=function(a){var b=G();var c=b.body;var d=b.createElement(ab);d.language=Mb;d.text=a;c.appendChild(d);c.removeChild(d)};function K(){var c={};var d;var e;var f=p.getElementsByTagName(Vb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(Wb),k;if(j){j=j.replace(Xb,fb);if(j.indexOf(Yb)>=X){continue}if(j==Zb){k=i.getAttribute($b);if(k){var l,m=k.indexOf(_b);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=fb}c[j]=l}}else if(j==ac){k=i.getAttribute($b);if(k){try{}catch(a){alert(bc+k+cc)}}}else if(j==dc){k=i.getAttribute($b);if(k){try{}catch(a){alert(bc+k+ec)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};B=d;embed.__errFn=e}
function L(){function e(a){var b=a.lastIndexOf(fc);if(b==-1){b=a.length}var c=a.indexOf(gc);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=X?a.substring(X,d+Y):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(hc);b.src=a+ic;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(jc);if(a!=null){return a}return fb}
function h(a){var b=a.match(/([^\\\/]+).nocache.js/g);return b?b[X]===kc:false}
function i(){embed.generatedTimestamp=null;if(null!=r.src&&h(r.src)){if(embed.generatedTimestamp&&embed.generatedTimestamp.length>X){var a=e(r.src);return e(a.substring(X,a.length-Y))+embed.generatedTimestamp+lc}else{return e(r.src)}}return fb}
function j(){var a=p.getElementsByTagName(mc);if(a.length>X){return a[a.length-Y].href}return fb}
function k(){var a=p.location;return a.href==a.protocol+cb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==fb){l=i()}if(l==fb){l=j()}if(l==fb&&k()){l=e(p.location.href)}l=f(l);return l}
function M(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return embed.__moduleBase+a}
function N(){var f=[];var g=X;function h(a,b){var c=f;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(B){B(a,d,b)}throw null}
j[nc]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(oc)!=-1}())return pc;if(function(){return a.indexOf(qc)!=-1&&(b>=$&&b<rc)}())return sc;if(function(){return a.indexOf(qc)!=-1&&(b>=tc&&b<rc)}())return uc;if(function(){return a.indexOf(qc)!=-1&&(b>=vc&&b<rc)}())return wc;if(function(){return a.indexOf(xc)!=-1||b>=rc}())return yc;return fb};i[nc]={'gecko1_8':X,'ie10':Y,'ie8':Z,'ie9':_,'safari':zc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};embed.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};embed.__computePropValue=k;o.__gwt_activeModules[kb].bindings=embed.__getPropMap;A(mb,Ac);if(w()){return M(Bc)}var l;try{h([sc],Cc);h([wc],Dc);h([uc],Ec);h([pc],Fc);h([yc],Gc);l=f[k(nc)];var m=l.indexOf(Hc);if(m!=-1){g=parseInt(l.substring(m+Y),$);l=l.substring(X,m)}}catch(a){}embed.__softPermutationId=g;return M(l+Ic)}
function O(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}A(Jc,nb);A(Jc,Kc)}
K();embed.__moduleBase=L();C[kb].moduleBase=embed.__moduleBase;var P=N();if(o){var Q=!!(o.location.protocol==Lc||o.location.protocol==Mc);o.__gwt_activeModules[kb].canRedirect=Q;function R(){var b=Nc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(Q&&R()){var S=Oc;var T=o.sessionStorage[S];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(T)){if(T&&(window.console&&console.log)){console.log(Pc+T)}T=fb}if(T&&!o[S]){o[S]=true;o[S+Qc]=L();var U=p.createElement(ab);U.src=T;var V=p.getElementsByTagName(Ib)[X];V.insertBefore(U,V.firstElementChild||V.children[X]);return false}}}O();A(mb,Kc);J(P);D();return true};embed.succeeded=embed();})();